import React, { useMemo, useState } from 'react';
import { AlertTriangle, ArrowRight, CheckCircle2, ChevronDown, CircleHelp, Database, FlaskConical, Search, Waypoints } from 'lucide-react';
import { GovinIssueClass, IncidentPrefill } from '../types';
import { ActionHint } from './ActionHint';

interface DirectionCheckViewProps { onCreateIncident: (prefill: IncidentPrefill) => void; }
type Integration = 'Нетрика' | 'Адыгея' | 'Брегис';
type DemoScenarioId = 'S1' | 'S2' | 'S3' | 'S4' | 'S5';
type StageState = 'ok' | 'error' | 'pending';
type StageId = 'services' | 'checkin' | 'delivery';
type MappingKind = 'Услуга' | 'Тест';
interface MappingRow { kind: MappingKind; invitroCode: string; invitroName: string; vendorCode: string; vendorName: string; status: 'Замапплено' | 'Нет маппинга' | 'Некорректный маппинг' | 'Нет данных'; }
interface StageCard { id: StageId; number: number; title: string; mappingType: string; state: StageState; summary: string; action: string; }
interface DemoDirection {
  scenario: DemoScenarioId; integration: Integration; barcode: string; externalId: string; client: string; clientCode: string; lpu: string; createdAt: string;
  inz: string[]; serviceName: string; assignedTests: string[]; deliveredResults: string[]; sourceStatus: string; databaseState: string;
  mappingRows: MappingRow[]; stages: StageCard[]; issueLabel?: string; issueClass?: GovinIssueClass; incidentTitle?: string; recommendedRoute?: string; incidentDescription?: string;
}

const integrations: Integration[] = ['Нетрика', 'Адыгея', 'Брегис'];
const demoDirections: DemoDirection[] = [
  { scenario: 'S1', integration: 'Нетрика', barcode: '1236514265', externalId: 'DIR-DEMO-001', client: 'Демо-клиент 1', clientCode: 'CLI-DEMO-01', lpu: 'ЛПУ · DEMO 01', createdAt: '21.08.2026 09:15', inz: ['942476082'], serviceName: 'Профиль обследования · DEMO', assignedTests: ['Тест A · качественный', 'Тест B · количественный'], deliveredResults: ['Тест A · результат доставлен', 'Тест B · результат доставлен'], sourceStatus: 'Доставка завершена', databaseState: 'Направление и заказ найдены в DEMO-БД', mappingRows: [
    { kind: 'Услуга', invitroCode: 'NMU-1001', invitroName: 'Услуга INVITRO · DEMO', vendorCode: 'V-SVC-77', vendorName: 'Услуга в МИС/ЛИС · DEMO', status: 'Замапплено' },
    { kind: 'Тест', invitroCode: 'NMU-T01', invitroName: 'Тест A · DEMO', vendorCode: 'V-T01', vendorName: 'Тест A в МИС/ЛИС', status: 'Замапплено' },
    { kind: 'Тест', invitroCode: 'NMU-T02', invitroName: 'Тест B · DEMO', vendorCode: 'V-T02', vendorName: 'Тест B в МИС/ЛИС', status: 'Замапплено' },
  ], stages: [
    { id: 'services', number: 1, title: 'Получение услуг / создание направления', mappingType: 'Маппинг услуг', state: 'ok', summary: 'Услуги сопоставлены корректно.', action: 'Ничего исправлять не требуется.' },
    { id: 'checkin', number: 2, title: 'Чекин', mappingType: 'Маппинг услуг', state: 'ok', summary: 'Повторная проверка услуг пройдена.', action: 'Направление может идти дальше по процессу.' },
    { id: 'delivery', number: 3, title: 'Доставка результатов', mappingType: 'Маппинг тестов', state: 'ok', summary: 'Все тесты сопоставлены, результаты доставлены.', action: 'Дополнительных действий нет.' },
  ]},
  { scenario: 'S2', integration: 'Адыгея', barcode: '2236514265', externalId: 'DIR-DEMO-002', client: 'Демо-клиент 2', clientCode: 'CLI-DEMO-02', lpu: 'ЛПУ · DEMO 02', createdAt: '21.08.2026 09:40', inz: [], serviceName: 'Услуга обследования · DEMO', assignedTests: [], deliveredResults: [], sourceStatus: 'Направление получено', databaseState: 'Направление найдено, внутренний заказ ещё не создан', mappingRows: [{ kind: 'Услуга', invitroCode: 'NMU-2001', invitroName: 'Услуга INVITRO · DEMO', vendorCode: 'V-SVC-88', vendorName: 'Услуга в МИС/ЛИС · DEMO', status: 'Нет маппинга' }], stages: [
    { id: 'services', number: 1, title: 'Получение услуг / создание направления', mappingType: 'Маппинг услуг', state: 'error', summary: 'Для одной услуги отсутствует маппинг.', action: 'Исправить маппинг до чекина и повторно убедиться, что услуга сопоставлена корректно.' },
    { id: 'checkin', number: 2, title: 'Чекин', mappingType: 'Маппинг услуг', state: 'pending', summary: 'Чекин ещё не выполнен.', action: 'После исправления маппинга система повторно проверит услуги на чекине.' },
    { id: 'delivery', number: 3, title: 'Доставка результатов', mappingType: 'Маппинг тестов', state: 'pending', summary: 'Этап ещё не наступил.', action: 'Контроль маппинга тестов выполняется только на этапе доставки результатов.' },
  ], issueLabel: 'Нет маппинга услуги', issueClass: 'SERVICE_MAPPING', incidentTitle: 'Ошибка маппинга услуги', recommendedRoute: 'Сопровождение маппинга', incidentDescription: 'На этапе создания направления отсутствует маппинг услуги. Нужно исправить сопоставление до чекина.' },
  { scenario: 'S3', integration: 'Брегис', barcode: '3236514265', externalId: 'DIR-DEMO-003', client: 'Демо-клиент 3', clientCode: 'CLI-DEMO-03', lpu: 'ЛПУ · DEMO 03', createdAt: '21.08.2026 10:05', inz: ['942476083'], serviceName: 'Услуга обследования · DEMO', assignedTests: ['Тест C · DEMO'], deliveredResults: [], sourceStatus: 'Нечекин', databaseState: 'Направление и внутренний заказ найдены', mappingRows: [{ kind: 'Услуга', invitroCode: 'NMU-3001', invitroName: 'Услуга INVITRO · DEMO', vendorCode: 'V-SVC-99', vendorName: 'Услуга в МИС/ЛИС · DEMO', status: 'Нет маппинга' }], stages: [
    { id: 'services', number: 1, title: 'Получение услуг / создание направления', mappingType: 'Маппинг услуг', state: 'ok', summary: 'На создании направление прошло контроль.', action: 'Переходим к повторной проверке на чекине.' },
    { id: 'checkin', number: 2, title: 'Чекин', mappingType: 'Маппинг услуг', state: 'error', summary: 'Нечекин вызван отсутствующим маппингом услуги.', action: 'Исправить маппинг услуги и направить заявку на ручное лабораторное исполнение.' },
    { id: 'delivery', number: 3, title: 'Доставка результатов', mappingType: 'Маппинг тестов', state: 'pending', summary: 'Доставка не началась.', action: 'После прохождения чекина перейти к контролю маппинга тестов.' },
  ], issueLabel: 'Нечекин / нет маппинга услуги', issueClass: 'SERVICE_MAPPING', incidentTitle: 'Нечекин из-за отсутствующего маппинга услуги', recommendedRoute: 'Исправление маппинга услуги + ручное лабораторное исполнение', incidentDescription: 'На этапе чекина отсутствует маппинг услуги. По регламенту нужно исправить маппинг услуги и направить заявку на ручное лабораторное исполнение.' },
  { scenario: 'S4', integration: 'Нетрика', barcode: '4236514265', externalId: 'DIR-DEMO-004', client: 'Демо-клиент 4', clientCode: 'CLI-DEMO-04', lpu: 'ЛПУ · DEMO 04', createdAt: '21.08.2026 10:30', inz: ['942476084'], serviceName: 'Профиль обследования · DEMO', assignedTests: ['Тест D · качественный', 'Тест E · количественный'], deliveredResults: [], sourceStatus: 'Доставка отменена', databaseState: 'Направление, заказ и результаты найдены; доставка не выполнена', mappingRows: [
    { kind: 'Услуга', invitroCode: 'NMU-4001', invitroName: 'Услуга INVITRO · DEMO', vendorCode: 'V-SVC-44', vendorName: 'Услуга в МИС/ЛИС · DEMO', status: 'Замапплено' },
    { kind: 'Тест', invitroCode: 'NMU-T04', invitroName: 'Тест D · DEMO', vendorCode: 'V-T04', vendorName: 'Тест D в МИС/ЛИС', status: 'Замапплено' },
    { kind: 'Тест', invitroCode: 'NMU-T05', invitroName: 'Тест E · DEMO', vendorCode: 'V-T05', vendorName: 'Тест E в МИС/ЛИС', status: 'Нет маппинга' },
  ], stages: [
    { id: 'services', number: 1, title: 'Получение услуг / создание направления', mappingType: 'Маппинг услуг', state: 'ok', summary: 'Маппинг услуг корректен.', action: 'Контроль пройден.' },
    { id: 'checkin', number: 2, title: 'Чекин', mappingType: 'Маппинг услуг', state: 'ok', summary: 'Чекин пройден.', action: 'Направление передано дальше.' },
    { id: 'delivery', number: 3, title: 'Доставка результатов', mappingType: 'Маппинг тестов', state: 'error', summary: 'У одного теста отсутствует маппинг. Доставка результатов отменена.', action: 'Исправить маппинг теста, загрузить корректный маппинг и повторно инициировать отправку результата.' },
  ], issueLabel: 'Ошибка доставки / нет маппинга теста', issueClass: 'TEST_MAPPING', incidentTitle: 'Ошибка доставки результатов', recommendedRoute: 'ГСТИ, если интеграция в поддержке; чат «Ежевика», если интеграция ещё на сопровождении разработки', incidentDescription: 'На этапе доставки отсутствует маппинг теста, поэтому доставка результатов отменена. Нужно исправить тестовый маппинг и повторно инициировать отправку результата.' },
  { scenario: 'S5', integration: 'Нетрика', barcode: '9999999999', externalId: '', client: '', clientCode: '', lpu: '', createdAt: '', inz: [], serviceName: '', assignedTests: [], deliveredResults: [], sourceStatus: 'Не найдено', databaseState: 'В DEMO-БД направление не найдено', mappingRows: [], stages: [], issueLabel: 'Направление не найдено в базе данных', issueClass: 'DATABASE_NOT_FOUND', incidentTitle: 'Направление не найдено в БД', recommendedRoute: 'Техническая поддержка / ГСТИ', incidentDescription: 'Направление не найдено по переданному идентификатору. Нужно проверить идентификатор, выбранную интеграцию и наличие данных в базе.' },
];

const stageStyles: Record<StageState, string> = { ok: 'border-emerald-200 bg-emerald-50', error: 'border-red-200 bg-red-50', pending: 'border-slate-200 bg-slate-50' };
const stageStatus: Record<StageState, string> = { ok: 'Пройден', error: 'Ошибка', pending: 'Ожидает' };
const scenarioLabels: Record<DemoScenarioId, string> = { S1: 'Успешный путь', S2: 'Нет маппинга услуги', S3: 'Нечекин / нет маппинга услуги', S4: 'Ошибка доставки', S5: 'Не найдено' };

export const DirectionCheckView: React.FC<DirectionCheckViewProps> = ({ onCreateIncident }) => {
  const [integration, setIntegration] = useState<Integration | ''>('');
  const [barcode, setBarcode] = useState('');
  const [result, setResult] = useState<DemoDirection | null>(null);
  const [notFound, setNotFound] = useState(false);
  const [validationMessage, setValidationMessage] = useState('');
  const [showDemo, setShowDemo] = useState(false);
  const [expandedStage, setExpandedStage] = useState<StageId | null>(null);
  const matchingScenario = useMemo(() => demoDirections.find((item) => item.integration === integration && item.barcode === barcode.trim()), [integration, barcode]);
  const clearResult = () => { setResult(null); setNotFound(false); setValidationMessage(''); setExpandedStage(null); };

  const handleSearch = () => {
    if (!integration) { setValidationMessage('Сначала выберите интеграцию.'); setResult(null); setNotFound(false); return; }
    if (!barcode.trim()) { setValidationMessage('Введите номер направления или штрихкод из алерта / чат-бота.'); setResult(null); setNotFound(false); return; }
    setValidationMessage(''); setExpandedStage(null);
    if (matchingScenario && matchingScenario.scenario !== 'S5') { setResult(matchingScenario); setNotFound(false); return; }
    setResult(null); setNotFound(true);
  };

  const selectScenario = (scenarioId: DemoScenarioId) => {
    const scenario = demoDirections.find((item) => item.scenario === scenarioId)!;
    setIntegration(scenario.integration); setBarcode(scenario.barcode); setValidationMessage(''); setExpandedStage(null);
    if (scenarioId === 'S5') { setResult(null); setNotFound(true); } else { setResult(scenario); setNotFound(false); }
  };

  const createIncident = (direction: DemoDirection) => {
    const failedStage = direction.stages.find((stage) => stage.state === 'error');
    onCreateIncident({ source: 'GOVIN-303', client: direction.client || undefined, clientCode: direction.clientCode || undefined, lpu: direction.lpu || undefined, vendor: direction.integration, inz: direction.inz.join(', '), contextLabel: `${direction.integration} · ${direction.issueLabel || direction.sourceStatus} · ${direction.barcode}`, incidentTitle: direction.incidentTitle || direction.issueLabel || 'Инцидент GOVIN', issueClass: direction.issueClass, processStage: failedStage?.title || 'Проверка направления', externalDirectionId: direction.externalId || undefined, barcode: direction.barcode, recommendedRoute: direction.recommendedRoute, description: `GOVIN v0.5.5 · ${direction.issueLabel || direction.sourceStatus}. Идентификатор направления: ${direction.barcode}. Этап: ${failedStage?.title || 'Проверка направления'}. Клиент: ${direction.client || 'нет данных'}. ЛПУ: ${direction.lpu || 'нет данных'}. ИНЗ: ${direction.inz.join(', ') || 'не присвоен / нет данных'}. Интеграция: ${direction.integration}. ${direction.incidentDescription || ''} Рекомендованный маршрут: ${direction.recommendedRoute || 'уточнить по регламенту'}.` });
  };

  const createNotFoundIncident = () => {
    if (!integration || !barcode.trim()) return;
    onCreateIncident({ source: 'GOVIN-303', vendor: integration, inz: '', contextLabel: `${integration} · направление не найдено · ${barcode.trim()}`, incidentTitle: 'Направление не найдено в БД', issueClass: 'DATABASE_NOT_FOUND', processStage: 'Проверка направления', barcode: barcode.trim(), recommendedRoute: 'Техническая поддержка / ГСТИ', description: `GOVIN v0.5.5 · Направление не найдено в базе данных. Идентификатор: ${barcode.trim()}. Интеграция: ${integration}. Клиент, ЛПУ и ИНЗ в GOVIN не определены. Требуется проверить идентификатор, интеграцию и наличие данных в базе. Рекомендованный маршрут: техническая поддержка / ГСТИ.` });
  };

  const activeStage = result?.stages.find((stage) => stage.id === expandedStage) || null;

  return <div className="max-w-6xl mx-auto space-y-3 py-2 pb-10 notranslate" translate="no">
    <div className="bg-white rounded-2xl border border-slate-200 px-5 py-4 shadow-xs"><div className="flex items-center gap-2 text-[#007f89] font-bold text-[11px] uppercase tracking-wider mb-1"><Waypoints className="w-4 h-4" /> GOVIN-303 · DEMO v0.5.5</div><h1 className="text-xl sm:text-2xl font-extrabold text-slate-900 leading-tight">Проверка направления и маппинга</h1><p className="text-xs sm:text-sm text-slate-500 mt-1">Получение услуг → чекин → доставка результатов</p></div>

    <div className="bg-white rounded-2xl border border-slate-200 px-5 py-4 shadow-xs"><div className="grid grid-cols-1 md:grid-cols-[25fr_60fr_15fr] gap-3 items-end">
      <label><span className="text-xs font-bold text-slate-700 block mb-1.5">Интеграция</span><select value={integration} onChange={(e) => { setIntegration(e.target.value as Integration | ''); clearResult(); }} className="w-full h-11 px-3 rounded-xl border border-slate-200 bg-slate-50 text-sm"><option value="">Выберите интеграцию</option>{integrations.map((item) => <option key={item}>{item}</option>)}</select></label>
      <label><span className="text-xs font-bold text-slate-700 flex flex-wrap items-center gap-x-2 mb-1.5">Номер направления / штрихкод <span className="font-normal text-slate-400">из алерта / чат-бота</span></span><input value={barcode} onChange={(e) => { setBarcode(e.target.value); clearResult(); }} onKeyDown={(e) => { if (e.key === 'Enter') handleSearch(); }} placeholder="Введите идентификатор направления" className="w-full h-11 px-3 rounded-xl border border-slate-200 bg-slate-50 text-sm" /></label>
      <ActionHint text="Проверит направление в выбранной интеграции и покажет этап, проблему и следующий шаг." className="w-full"><button type="button" onClick={handleSearch} className="w-full h-11 px-4 rounded-xl bg-[#0099a8] hover:bg-[#007f89] text-white text-sm font-bold inline-flex items-center justify-center gap-2"><Search className="w-4 h-4" /> Найти</button></ActionHint>
    </div>{validationMessage && <div role="alert" className="mt-2 text-xs font-semibold text-red-600">{validationMessage}</div>}<div className="mt-3 pt-3 border-t border-slate-100"><button type="button" onClick={() => setShowDemo((v) => !v)} className="text-xs font-bold text-slate-500 hover:text-[#007f89]">{showDemo ? 'Скрыть демо-сценарии' : 'Демо-сценарии'} {showDemo ? '↑' : '↓'}</button>{showDemo && <div className="flex flex-wrap gap-2 mt-2">{(Object.keys(scenarioLabels) as DemoScenarioId[]).map((id) => <button key={id} type="button" onClick={() => selectScenario(id)} className="px-3 py-1.5 rounded-full border border-slate-200 bg-slate-50 hover:bg-slate-100 text-xs font-semibold">{id} · {scenarioLabels[id]}</button>)}</div>}</div></div>

    {notFound && <div className="bg-white rounded-2xl border border-amber-200 p-5 shadow-xs"><div className="flex gap-3"><CircleHelp className="w-5 h-5 text-amber-600 mt-0.5"/><div className="flex-1"><h2 className="font-extrabold text-slate-900">Направление не найдено</h2><p className="text-sm text-slate-600 mt-1">Проверьте идентификатор и выбранную интеграцию. Если данных нет в базе, эскалируйте в техническую поддержку.</p><div className="mt-3 text-xs rounded-lg border border-amber-200 bg-amber-50 p-3"><strong>Маршрут:</strong> техническая поддержка / ГСТИ.</div><ActionHint text="Откроется форма ПРИИЗ. Интеграция, идентификатор и причина «не найдено» будут перенесены автоматически." className="mt-4"><button type="button" onClick={createNotFoundIncident} className="px-4 py-2 rounded-lg border border-[#8bd2d6] bg-white text-[#007f89] font-bold text-sm inline-flex items-center gap-2 hover:bg-[#e9f8f8]">Создать обращение в ПРИИЗ <ArrowRight className="w-4 h-4"/></button></ActionHint></div></div></div>}

    {result && <>
      <div className={`rounded-2xl border px-4 py-3 ${result.issueLabel ? 'border-red-200 bg-red-50' : 'border-emerald-200 bg-emerald-50'}`}><div className="flex items-start gap-3">{result.issueLabel ? <AlertTriangle className="w-5 h-5 text-red-600 mt-0.5 shrink-0"/> : <CheckCircle2 className="w-5 h-5 text-emerald-600 mt-0.5 shrink-0"/>}<div><div className="text-[11px] font-black uppercase tracking-wide text-slate-600">Итог проверки</div><h2 className="font-extrabold text-slate-900 mt-0.5">{result.issueLabel || 'Проблем не обнаружено'}</h2><p className="text-sm text-slate-700 mt-1">{result.stages.find((s) => s.state === 'error')?.action || 'Направление прошло доступные контрольные этапы. Дополнительных действий не требуется.'}</p></div></div></div>

      <section aria-label="Данные направления" className="bg-white rounded-2xl border border-slate-200 shadow-xs px-4 py-3"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 pb-2 border-b border-slate-100"><div className="flex items-center gap-2 flex-wrap"><strong className="font-mono text-sm text-slate-900">{result.externalId}</strong><span className="text-xs text-slate-400">{result.integration}</span></div><span className="px-2.5 py-1 rounded-full bg-slate-100 text-slate-700 text-[11px] font-bold">{result.sourceStatus}</span></div><dl className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-x-5 gap-y-2 pt-3 text-sm"><div><dt className="text-[11px] text-slate-400">Клиент / ЛПУ</dt><dd className="font-bold text-slate-800">{result.client} <span className="font-normal text-slate-500">· {result.lpu}</span></dd></div><div><dt className="text-[11px] text-slate-400">Создано / ИНЗ</dt><dd className="font-bold text-slate-800">{result.createdAt} <span className="font-normal text-slate-500">· {result.inz.join(', ') || 'Не присвоен'}</span></dd></div><div><dt className="text-[11px] text-slate-400">Услуга / штрихкод</dt><dd className="font-bold text-slate-800">{result.serviceName} <span className="font-mono font-normal text-slate-500">· {result.barcode}</span></dd></div><div><dt className="text-[11px] text-slate-400">База данных</dt><dd className="font-bold text-slate-800">{result.databaseState}</dd></div></dl></section>

      <section aria-label="Этапы проверки" className="bg-white rounded-2xl border border-slate-200 shadow-xs p-3"><div className="grid grid-cols-1 md:grid-cols-3 gap-2">{result.stages.map((stage) => <button key={stage.id} type="button" aria-expanded={expandedStage === stage.id} aria-controls={`stage-detail-${stage.id}`} onClick={() => setExpandedStage((current) => current === stage.id ? null : stage.id)} className={`w-full text-left rounded-xl border px-3 py-2.5 transition ${stageStyles[stage.state]} hover:shadow-sm focus:outline-none focus:ring-2 focus:ring-[#0099a8]/30`}><div className="flex items-center justify-between gap-2"><span className="text-[11px] font-black text-slate-600">Этап {stage.number}</span><span className={`text-[10px] font-black uppercase tracking-wide ${stage.state === 'ok' ? 'text-emerald-700' : stage.state === 'error' ? 'text-red-700' : 'text-slate-500'}`}>{stageStatus[stage.state]}</span></div><div className="flex items-start justify-between gap-2 mt-1"><div><div className="font-extrabold text-sm text-slate-900 leading-tight">{stage.title}</div><div className="text-[11px] text-slate-500 mt-1">{stage.mappingType}</div></div><ChevronDown className={`w-4 h-4 shrink-0 text-slate-500 transition-transform ${expandedStage === stage.id ? 'rotate-180' : ''}`}/></div></button>)}</div>{activeStage && <div id={`stage-detail-${activeStage.id}`} className={`mt-2 rounded-xl border px-3 py-3 ${stageStyles[activeStage.state]}`}><div className="grid grid-cols-1 md:grid-cols-3 gap-3 text-xs"><div><div className="font-black uppercase tracking-wide text-slate-500 text-[10px]">Что проверяем</div><div className="font-bold text-slate-800 mt-1">{activeStage.mappingType}</div></div><div><div className="font-black uppercase tracking-wide text-slate-500 text-[10px]">Что увидели</div><div className="text-slate-700 mt-1">{activeStage.summary}</div></div><div><div className="font-black uppercase tracking-wide text-slate-500 text-[10px]">Действие ДКП</div><div className="text-slate-700 mt-1">{activeStage.action}</div></div></div></div>}</section>

      <div className="bg-white rounded-2xl border border-slate-200 p-4 shadow-xs"><div className="flex items-center gap-2 mb-3"><Database className="w-5 h-5 text-[#0099a8]"/><h2 className="font-extrabold text-slate-900">Сводка маппинга</h2></div><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="text-left border-b border-slate-200"><th className="py-2 pr-3">Тип</th><th className="py-2 pr-3">Код INVITRO / НМУ</th><th className="py-2 pr-3">Название INVITRO</th><th className="py-2 pr-3">Код вендора</th><th className="py-2 pr-3">Название в МИС/ЛИС</th><th className="py-2">Статус</th></tr></thead><tbody>{result.mappingRows.map((row, i) => <tr key={`${row.kind}-${i}`} className="border-b border-slate-100"><td className="py-3 pr-3 font-bold">{row.kind}</td><td className="py-3 pr-3 font-mono">{row.invitroCode}</td><td className="py-3 pr-3">{row.invitroName}</td><td className="py-3 pr-3 font-mono">{row.vendorCode}</td><td className="py-3 pr-3">{row.vendorName}</td><td className="py-3"><span className={`px-2 py-1 rounded-full font-bold ${row.status === 'Замапплено' ? 'bg-emerald-50 text-emerald-700' : row.status === 'Нет данных' ? 'bg-slate-100 text-slate-600' : 'bg-red-50 text-red-700'}`}>{row.status}</span></td></tr>)}</tbody></table></div></div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-3"><div className="bg-white rounded-2xl border border-slate-200 p-4"><div className="flex items-center gap-2"><FlaskConical className="w-5 h-5 text-[#0099a8]"/><h3 className="font-extrabold">Тесты и результаты</h3></div><div className="mt-3 text-xs"><strong>Назначенные тесты:</strong> {result.assignedTests.join(', ') || 'Нет данных'}</div><div className="mt-2 text-xs"><strong>Доставленные результаты:</strong> {result.deliveredResults.join(', ') || (result.scenario === 'S4' ? 'Не доставлены — доставка отменена' : 'Нет данных')}</div></div><div className="bg-white rounded-2xl border border-slate-200 p-4"><h3 className="font-extrabold">Что делать дальше</h3><p className="text-sm text-slate-700 mt-2">{result.recommendedRoute ? <>Рекомендованный маршрут: <strong>{result.recommendedRoute}</strong>.</> : 'Регламентных действий не требуется.'}</p>{result.issueLabel && <ActionHint text="Откроется форма ПРИИЗ. Из GOVIN автоматически перенесутся известные данные направления, интеграция и причина проблемы." className="mt-4"><button type="button" onClick={() => createIncident(result)} className="px-4 py-2 rounded-lg border border-[#8bd2d6] bg-white text-[#007f89] font-bold text-sm inline-flex items-center gap-2 hover:bg-[#e9f8f8]">Создать обращение в ПРИИЗ <ArrowRight className="w-4 h-4"/></button></ActionHint>}</div></div>
    </>}

    <details className="rounded-xl border border-slate-100 bg-slate-50/60 px-3 py-2 text-[10px] text-slate-400"><summary className="cursor-pointer select-none">О DEMO</summary><div className="pt-2">Регламент основан на валидации команды ДКП от 21.08.2026. Используются только вымышленные данные. Точные production API, состав mapping-полей и маршруты команд остаются TBD до Technical Discovery.</div></details>
  </div>;
};